---
pagetitle: "Snapping Points to Nearest Line"
---

<br>

## Snapping Points to Nearest Line


```{r libseval, eval=T, echo=F, message=F, show=FALSE}

suppressPackageStartupMessages({
  library(here);
  library(dplyr);
  library(viridis);
  library(ggplot2);
  library(lubridate);
  library(leaflet);
  library(sf);
  library(mapview);
  library(USAboundaries) # STATES/counties data
})

```

### With NANN

```{r}

library(RANN)

# use the grid centroids and outline from pr_cnty:

# get coordinate matrices, could be points and lines or lines and points
grid_coords <- do.call(rbind, st_geometry(grid_centroids))
grid_coords <- cbind(grid_coords, 1:nrow(grid_coords)) # add unique row ID
graph_coords <- do.call(rbind, st_geometry(pr_cnty))[[1]][1][[1]] # make as vector
graph_coords <- cbind(graph_coords, 1:nrow(graph_coords)) # add unique row ID

# fast nearest neighbour search
closest <- nn2(grid_coords[,1:2], graph_coords[,1:2], k = 1, searchtype = "radius", radius = 0.019) # about ~800 meters

closest <- sapply(closest, cbind) %>% as_tibble
grid_pts <- graph_coords %>% as_tibble() %>% rename(lon=V1, lat=V2, idx=V3)
tst <- left_join(grid_pts, closest, by=c("idx"="nn.idx"))
tst_sf <- st_as_sf(tst, coords = c("lon","lat"), remove = FALSE)

plot(pr_cnty$geometry, axes=TRUE, 
     bgc=adjustcolor(col = "dodgerblue", alpha.f = 0.5),
     col="white")

plot(grid_centroids, add=TRUE, bg="maroon", pch=21)
plot(tst_sf$geometry, add=T, pch=16, col="pink")

mapview(grid_centroids) + mapview(tst_sf)

```


### Custom Function

Custom function to move points to nearest line:

```{r}
library(sf)
library(mapview)
st_snap_points = function(x, y, max_dist = 1000) {
        
        if (inherits(x, "sf")) n = nrow(x)
        if (inherits(x, "sfc")) n = length(x)
        
        out = do.call(c,
                      lapply(seq(n), function(i) {
                          nrst = st_nearest_points(st_geometry(x)[i], y)
                          nrst_len = st_length(nrst)
                          nrst_mn = which.min(nrst_len)
                          if (as.vector(nrst_len[nrst_mn]) > max_dist) return(st_geometry(x)[i])
                          return(st_cast(nrst[nrst_mn], "POINT")[2])
                      })
        )
        return(out)
    }

tst = st_snap_points(brew, trails, 1100) # distance 
mapview(breweries) + mapview(tst, col.regions = "yellow") + trails
```


## Create Sample Random Points from Polygon

Also make a grid and get centroids

```{r}

us <- USAboundaries::us_states(resolution = "high", states=c()) # all states
pr <- us %>% filter(stusps == "PR")

pr_cnty <- USAboundaries::us_counties(resolution = "high", states="PR") %>% filter(name=="Vieques")

plot(pr$geometry, bgc=adjustcolor(col = "dodgerblue", alpha.f = 0.5), 
     col="white", graticule=TRUE, col_graticule="gray", axes=TRUE)
plot(pr_cnty$geometry, add=TRUE, axes=FALSE, col=adjustcolor("green3",alpha=0.2))

plot(pr_cnty$geometry, axes=TRUE, 
     bgc=adjustcolor(col = "dodgerblue", alpha.f = 0.5),
     col="white")
pts <- st_sample(pr_cnty, size = 25, type="random")
plot(pts, add=T, col="orange", pch=16)

# make a grid:
grid1 <- st_make_grid(pr_cnty, what = "polygons")
grid2 <- st_make_grid(pr_cnty, cellsize = .01, square = FALSE)
plot(grid1, add=T, col=NA, border="purple")
plot(grid2, add=T, col=NA, border="blue")

# get centroid of hex:
grid_centroids <- st_centroid(grid2)
plot(grid_centroids, add=TRUE, bg="maroon", pch=21)

```

